version: '2.4'

services:
  web:
    build: ./app
    container_name: web
    volumes:
      - ./app/:/app
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      
  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 80:80
      depends_on:
        - web
    
volumes:
  postgres_data:
